### ISSUE TITLE
Coin selection algorithm selects too small utxo

### ISSUE THREAD

**Issue by onvej-sl** [trezor/WalletWasabi#16]
See https://github.com/zkSNACKs/WalletWasabi/issues/10759.

**Comment by szymonlesisz** [comment]
temporary fixed in suite: https://github.com/trezor/trezor-suite/pull/8622

**Comment by onvej-sl** [comment]
Fixed by adopting https://github.com/zkSNACKs/WalletWasabi/pull/10842. See https://github.com/trezor/WalletWasabi/commit/c5b05675d8acd1d880f78a24585920615371a5f7 and https://github.com/trezor/WalletWasabi/commit/a4b91c9ae2eb5383642aaf014e2ddecc67c403e2.
